### ISSUE TITLE
Inconsistent Value formatting

### ISSUE THREAD

**Issue by LukasZahradnik** [GustikS/NeuraLogic#4]
## Current behavior:

- `ScalarValue::toString()` formats the value to 10 decimal places (`Settings.detailedNumberFormat`).
- `VectorValue::toSring()` formats the value to 2 decimal places (`Settings.shortNumberFormat`).
- `MatrixValue::toString()` does not use number formatter - formats numbers to 16 decimal places.
- `One::toString()` formats the value to 0 decimal places.
- `Zero::toString()` formats the value to 0 decimal places.

This behavior results in inconsistent numbers rendering and larger rendered graphs (because matrices strings are too wide).
The drawing/rendering looks like it is supposed to be customizable via `Drawer.numberFormat` property, but this property is not used anywhere.

## Expected behavior:

At least non-constant values (Scalar, Vector, and Matrix) use the same (parametrized) number formatter.

**Comment by GustikS** [comment]
Thanks for this clearly written issue, it should be solved now by 53a8be12f54f90c7f35f1a281cbc3ad983ac4f57
