### ISSUE TITLE
SoftEntropy overflow resulting in NaN

### ISSUE THREAD

**Issue by LukasZahradnik** [GustikS/NeuraLogic#6]
## The bug description

The SoftEntropy error function produces NaN values for higher input values.
I identified problems in three different places:
- Softmax computation https://github.com/GustikS/NeuraLogic/blob/master/Algebra/src/main/java/cz/cvut/fel/ida/algebra/functions/specific/SoftEntropy.java#L75
	`Math.exp` goes to infinity - should be fixable with `exp(input[i] - max(input))`

- Scalar softentropy - https://github.com/GustikS/NeuraLogic/blob/master/Algebra/src/main/java/cz/cvut/fel/ida/algebra/functions/specific/SoftEntropy.java#L33
`Math.exp` goes to infinity

- Vector softentropy -
https://github.com/GustikS/NeuraLogic/blob/master/Algebra/src/main/java/cz/cvut/fel/ida/algebra/functions/specific/SoftEntropy.java#L47
`Math.log` goes to -Infinity for zero and multiplication with zero targets results into NaN  

## Steps to reproduce
```java
        VectorValue in = new VectorValue(
                new double[] {
                        19056.858719905307, 4960.272544490949, 11971.046875371912,
                        5381.27145922252, 12381.873594408318, 4820.585859773736
                }
        );

        VectorValue target = new VectorValue(new double[] {0, 0, 0, 0, 0, 1});

        System.out.println(new SoftEntropy().evaluate(in, target));
        System.out.println(new SoftEntropy().differentiate(in, target));
```
Outputs:
```
NaN
[NaN,NaN,NaN,NaN,NaN,NaN]
```

**Comment by GustikS** [comment]
Thanks for a very clear bug report! 
This is a classic deep learning issue - solved with LogSumExp trick for numeric stability, which I was too lazy to incorporate back then (it was in the class as an open TODO).
Should be solved now with ac9cffe340d9b399d
